Let's begin with a circle. [browser: let c1 = circle(50, "red")]
Next, let's add a cube. [td: let b1 = box(0.5, "blue")]
Now let's move the cube to the right. [td: move(b1, 1.0, 0.0, 0.0)]
And rotate it forty five degrees. [td: rotate(b1, 0, 45, 0)]
Let's move that red circle over. [browser: move(c1, -0.5, 0.5, 0.0)]
Let's add a second cube in green. [td: let b2 = box(0.75, "green")]
Move it to the left and up. [td: move(b2, -1.0, 0.5, 0.0)]
And rotate it continuously. [td: rotate(b2, "me.time.frame", "me.time.frame", 0.0)]
Great, how fun!