
Let's play with text:
  [let t = browser_2d.text("Time: " + TIME.t.toFixed(1), 400, 270, 100, "cyan")]

  [browser_2d.text("Mic: " + MIC.audio_level.toFixed(1), 400, 370, 100, "red")]

  [let x = () => (10 * MIC.audio_level)]

  [browser_2d.text("Mic*10: " + x().toFixed(1), 400, 470, 100, "yellow")]

  [browser_2d.text("Words completed: " + SCRIPT.words_completed(), 400, 570, 100, "lightgreen")]

Let's begin with a circle.
  [let c1 = browser_2d.circle(() => 50 * MIC.audio_level + TIME.t, TIME.t < 10 ? "lime" : "red")]

A cube appears.
 [let block = browser_3d.cube(1.2, 1.2, 1.2, "gray")] [browser_3d.rotate(block,
                    TIME.t * MIC.audio_level,
                    TIME.t * 20,
                    0)]

Let's begin with a circle. [let c1 = browser_2d.circle(50, "red")]

Now another. [let c1 = browser_2d.circle(50, "green")]

