
Let's play with text:
  [let t = text((c)=>("Time: " + c.t.toFixed(1)), 400, 270, 100, "cyan")]

  [text((c)=>("Mic: " + c.audioLevel.toFixed(1)), 400, 370, 100, "red")]

  [let x = (c)=>(10*c.audioLevel)]

  [text((c)=>("Mic*10: " + x(c).toFixed(1)), 400, 470, 100, "yellow")]

Let's begin with a circle. 
  [let c1 = circle((c) => 50 * c.audioLevel + c.t, (c) => c.t < 10 ? "lime" : "red")]

A cube appears. 
 [browser_3d: let block = cube(1.2, 1.2, 1.2, "gray")] [browser_3d: rotate(block, 
                     (c)=>c.t*c.audioLevel, 
                    "t * 20", 
                    0)]

Let's begin with a circle. [browser_2d: let c1 = circle(50, "red")]

Now another. [browser_2d: let c1 = circle(50, "green")]

